
spring:
  datasource:
    url: jdbc:mysql://101.133.235.188/Sun_Data?useSSL=false&serverTimezone=UTC
    username: dev
    password: dev12345
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml