
spring:
  datasource:
    url: jdbc:mysql://101.133.235.188/SunBest?useSSL=false&serverTimezone=UTC
    username: root
    password: WHUTjnjp123456**
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

server:
    port: 80 

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml